finished rest of examples

diff --git a/examples/Makefile b/examples/Makefile
--- a/examples/Makefile
+++ b/examples/Makefile
@@ -1,6 +1,6 @@
 SRC := ./src
-BIN := ./bin
 REF := ./ref
+BIN := ./bin
 
 SRCS := $(wildcard $(SRC)/*.jpl)
 BINS := $(patsubst $(SRC)/%.jpl, $(BIN)/%, $(SRCS))
@@ -9,34 +9,36 @@ SUB := test/subtract
 
 all: $(BINS)
 $(BIN)/%: $(SRC)/%.jpl
-	@mkdir -p $(BIN)
+	@mkdir -p bin
 	./jplc $^ -o $@
 
 run/%: $(BIN)/%
-	$^
-
+	@$^
 
 test: all $(patsubst $(BIN)/%, test/%, $(BINS))
-test/%: $(BIN)/%
-	$(eval IMG := $(patsubst test/%, %.png, $@))
-	@if [ "$(IMG)" == "subtract.png" ]; then \
-		OUTPUT="$$($(BIN)/subtract)"; \
-		if [[ $$OUTPUT == "999999999.900000" ]]; then \
-			echo "subtract: PASS"; \
-		else \
-			echo "subtract: FAIL"; \
-		fi \
+test/subtract: $(BIN)/subtract
+	@OUTPUT="$$($(BIN)/subtract)"; \
+	if [[ $$OUTPUT == "999999999.900000" ]]; then \
+		printf "%-20s %s\n" "subtract" "PASSED"; \
 	else \
-		$^ $(REF)/sample.png && \
-		cmp -s $(IMG) $(REF)/$(IMG); \
-		RETVAL=$$?; \
-		if [ $$RETVAL -eq 0 ]; then \
-			echo "$(IMG): PASS"; \
-		else \
-			echo "$(IMG): FAIL"; \
-		fi \
+		printf "%-20s %s\n" "subtract" "FAILED"; \
+	fi
+
+test/red: bin/red run/red cmp/red.png
+test/circle: bin/circle run/circle cmp/circle.png
+test/invert: bin/invert run/invert cmp/sample-inverted.png
+test/sepia: bin/sepia run/sepia cmp/sample-sepia.png
+test/blur: bin/blur run/blur cmp/sample-blurred.png
+
+cmp/%: %
+	@cmp -s $^ $(REF)/$^; \
+	RETVAL=$$?
+	@if [[ $$RETVAL -eq 0 ]]; then \
+		printf "%-20s %s\n" "$^" "PASSED"; \
+	else \
+		printf "%-20s %s\n" "$^" "FAILED"; \
 	fi
 
 clean:
 	rm -rf $(BIN)
-	rm -rf ./*.png
+	rm -f red.png circle.png sample-inverted.png sample-sepia.png sample-blurred.png
